In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from data_analyzer import data_loader as dl
from data_analyzer import preprocessor as ppr

# Import Danych

In [3]:
path_pozary="../data/pozary.csv"
path_powierzchnie="../data/powierzchnie.xlsx"
path_populacja="../data/populacja.xls"
path_alkohol="../data/alkohol.csv"

In [4]:
pozary=dl.load_data(path_pozary)
powierzchnie=dl.load_data(path_powierzchnie)
populacja=dl.load_data(path_populacja)
alkohol=dl.load_data(path_alkohol)

INFO: Wczytanie pliku CSV zakończone pomyślnie.
INFO: Wczytanie pliku Excel zakończone pomyślnie.
INFO: Wczytanie pliku Excel zakończone pomyślnie.
INFO: Wczytanie pliku CSV zakończone pomyślnie.


In [5]:
pozary

TERYT         Województwo         Powiat         Gmina  \
0      20101        dolnośląskie  bolesławiecki   Bolesławiec   
1      20102        dolnośląskie  bolesławiecki   Bolesławiec   
2      20103        dolnośląskie  bolesławiecki      Gromadka   
3      20104        dolnośląskie  bolesławiecki  Nowogrodziec   
4      20105        dolnośląskie  bolesławiecki    Osiecznica   
...      ...                 ...            ...           ...   
2514  321804  zachodniopomorskie        łobeski         Resko   
2515  321805  zachodniopomorskie        łobeski     Węgorzyno   
2516  326101  zachodniopomorskie       Koszalin      Koszalin   
2517  326201  zachodniopomorskie       Szczecin      Szczecin   
2518  326301  zachodniopomorskie    Świnoujście   Świnoujście   

      RAZEM Pożar (P)  Mały (P/M)  Średni (P/Ś)  Duży (P/D)  \
0                  79          77             2           0   
1                  75          73             2           0   
2                  66          63             2           1   
3                 155         149             6           0   
4                  41          41             0           0   
...               ...         ...           ...         ...   
2514               35          35             0           0   
2515               47          44             3           0   
2516              219         212             5           2   
2517              890         879            10           1   
2518              120         117             3           0   

      Bardzo duży (P/BD)  RAZEM Miejscowe zagrożenie (MZ)  Małe (MZ/M)  \
0                      0                              366           53   
1                      0                              427           67   
2                      0                               77           10   
3                      0                              197           23   
4                      0                               98           11   
...                  ...                              ...          ...   
2514                   0                              105            5   
2515                   0                               95            6   
2516                   0                              650          123   
2517                   0                             1955          281   
2518                   0                              376           70   

      Lokalne (MZ/L)  Średnie (MZ/Ś)  Duże (MZ/D)  \
0                294              18            1   
1                333              22            5   
2                 63               3            1   
3                164               8            2   
4                 85               2            0   
...              ...             ...          ...   
2514             100               0            0   
2515              87               2            0   
2516             518               9            0   
2517            1644              28            2   
2518             301               5            0   

      Gigantyczne lub klęska żywiołowa (MZ/K)  RAZEM Alarm fałszywy (AF)  \
0                                           0                         61   
1                                           0                         23   
2                                           0                         10   
3                                           0                         18   
4                                           0                         14   
...                                       ...                        ...   
2514                                        0                         14   
2515                                        0                          8   
2516                                        0                        147   
2517                                        0                        445   
2518                                        0                        292   

      Złośliwy (A/Z)  W dobrej

In [6]:
powierzchnie

TERYT        Nazwa jednostki  Powierzchnia [ha]  \
0             00                 POLSKA           31393293   
1             02      WOJ. DOLNOŚLĄSKIE            1994714   
2        02 01     Powiat bolesławiecki             130351   
3     02 01 01 1            Bolesławiec               2285   
4     02 01 02 2            Bolesławiec              28913   
...          ...                    ...                ...   
4334  32 61 01 1            M. Koszalin              10557   
4335     32 62       Powiat m. Szczecin              30062   
4336  32 62 01 1            M. Szczecin              30062   
4337     32 63    Powiat m. Świnoujście              20206   
4338  32 63 01 1         M. Świnoujście              20206   

      Powierzchnia [km2]  Unnamed: 4  \
0                 313933         NaN   
1                  19947         NaN   
2                   1304         NaN   
3                     23         NaN   
4                    289         NaN   
...                  ...         ...   
4334                 106         NaN   
4335                 301         NaN   
4336                 301         NaN   
4337                 202         NaN   
4338                 202         NaN   

                                             Unnamed: 5  
0     Kolumna „Powierzchnia [km2]” prezentuje dane o...  
1     Powierzchnie wszystkich rodzajów jednostek pod...  
2     Wobec zastosowania reguły Kryłowa-Bradisa suma...  
3                                                   NaN  
4                                                   NaN  
...                                                 ...  
4334                                                NaN  
4335                                                NaN  
4336                                                NaN  
4337                                                NaN  
4338                                                NaN  

[4339 rows x 6 columns]

In [7]:
populacja

TABL. IV. LUDNOŚĆ, RUCH NATURALNY ORAZ MIGRACJE LUDNOŚCI WEDŁUG GMIN W 2024 R.  \
0                      POPULATION, VITAL STATISTICS ...                               
1                                                   NaN                               
2               Województwa\nVoivodships\nGminy\nGminas                               
3                                                   NaN                               
4                                                   NaN                               
...                                                 ...                               
3917                                        M.Węgorzyno                               
3918                                        G.Węgorzyno                               
3919                                         M.Koszalin                               
3920                                         M.Szczecin                               
3921                                      M.Świnoujście                               

                            Unnamed: 1  \
0                                  NaN   
1                                  NaN   
2     Identyfikator terytorialny\nCode   
3                                  NaN   
4                                  NaN   
...                                ...   
3917                           3218054   
3918                           3218055   
3919                           3261011   
3920                           3262011   
3921                           3263011   

                                             Unnamed: 2  \
0                                                   NaN   
1                                                   NaN   
2     Ludność\n(stan w dniu 31.12)\nPopulation\n(as ...   
3                                                   NaN   
4                                                   NaN   
...                                                 ...   
3917                                               2590   
3918                                               3657   
3919                                             105263   
3920                                             386706   
3921                                              38541   

                   Unnamed: 3                    Unnamed: 4        Unnamed: 5  \
0                         NaN                           NaN               NaN   
1                         NaN                           NaN               NaN   
2     Małżeń-stwa \nMarriages  Urodzenia żywe \nLive births  Zgony   \nDeaths   
3                         NaN                           NaN    ogółem \ntotal   
4                         NaN                           NaN               NaN   
...                       ...                           ...               ...   
3917                       10                            15                39   
3918                        6                            15                47   
3919                      390                           621              1243   
3920                     1729                          2588              4419   
3921                      151                           193               487   

                             Unnamed: 6  \
0                                   NaN   
1                                   NaN   
2                                   NaN   
3     w tym niemowląt \nof which infant   
4                                   NaN   
...                                 ...   
3917                                  -   
3918                                  -   
3919                                  1   
3920                                  5   
3921                                  -   

                                 Unnamed: 7  \
0                                       NaN   
1                                       NaN   
2     Przyrost naturalny \nNatural increase   
3                                       NaN   
4                    

In [8]:
alkohol

Numer zezwolenia                                        Nazwa firmy  \
0             394/23      AMKA  Spółka z ograniczoną odpowiedzialnością   
1             404/23   WORMAR K Spółka z ograniczoną odpowiedzialnością   
2             407/23                                    RAFAŁ DZILIŃSKI   
3             5/W/24  ALKOSWIAT Spółka z ograniczoną odpowiedzialnością   
4             6/W/24             Matyl Fenikost Aleksadra Matyl-Stawowy   
..               ...                                                ...   
411            22/25  MAXIM DYSTRYBUCJA Spółka z ograniczoną odpowie...   
412            24/25            WOLF AND OAK DISTILLERY  Spółka Akcyjna   
413            27/25  IRJAN Spółka z ograniczoną odpowiedzialnością ...   
414            31/25                         MAŁEK HURT Paweł Małkowski   
415            35/25      DRAKE Spółka z ograniczoną odpowiedzialnością   

    Kod pocztowy           Miejscowość                         Adres  \
0         02-972              Warszawa  Aleja Rzeczypospolitej 18/83   
1         83-300               Kartuzy                ul. Zamkowa 23   
2         06-400             Ciechanów                 ul. Leśna 52    
3         43-300         Bielsko-Biała     ul. Wincentego Witosa 170   
4         34-212             Bieńkówka                 Bienkówka 454   
..           ...                   ...                           ...   
411       08-400              Garwolin             ul. Parysowska 2    
412       80-864                Gdańsk           ul. Jana z Kolna 11   
413       63-600                 Kępno                  Mianowice 1G   
414       09-412  Stare Proboszczewice  ul. Stefana Mazowieckiego 18   
415       64-060               Wolkowo             Maksymilianowo 40   

            Województwo Data ważności  
0      WOJ. MAZOWIECKIE    2025-02-28  
1        WOJ. POMORSKIE    2025-03-03  
2      WOJ. MAZOWIECKIE    2025-02-21  
3          WOJ. ŚLĄSKIE    2025-03-30  
4      WOJ. MAŁOPOLSKIE    2025-04-20  
..                  ...           ...  
411    WOJ. MAZOWIECKIE    2026-01-21  
412      WOJ. POMORSKIE    2026-01-31  
413  WOJ. WIELKOPOLSKIE    2026-01-31  
414    WOJ. MAZOWIECKIE    2026-01-31  
415  WOJ. WIELKOPOLSKIE    2026-01-31  

[416 rows x 7 columns]

# PREPROCESSING

Chcemy zestawić ze sobą dane w 4 powyższych plikach. Żeby to zrobić musimy połączyć kody gmin pierwszych trzech zbiorów danych, tak aby ze sobą pasowały.
Widzimy, że dane o koncesjach alkoholu nie mają kolumny z kodem, będziemy je mogli zatem łączyć albo Miejscowością, albo Województwem.
Zanim to jednak zrobimy, usuńmy niepotrzebne wiersze i kolumny z tych zbiorów.

## wybieranie tylko interesujących nas kolumn

In [9]:
pozary=pozary.iloc[:,:5]
pozary=ppr.zmien_nazwe(pozary, "RAZEM Pożar (P)", "Liczba Pożarów")
pozary

INFO: Zmieniono nazwę kolumny 'RAZEM Pożar (P)' na 'Liczba Pożarów'.


TERYT         Województwo         Powiat         Gmina  Liczba Pożarów
0      20101        dolnośląskie  bolesławiecki   Bolesławiec              79
1      20102        dolnośląskie  bolesławiecki   Bolesławiec              75
2      20103        dolnośląskie  bolesławiecki      Gromadka              66
3      20104        dolnośląskie  bolesławiecki  Nowogrodziec             155
4      20105        dolnośląskie  bolesławiecki    Osiecznica              41
...      ...                 ...            ...           ...             ...
2514  321804  zachodniopomorskie        łobeski         Resko              35
2515  321805  zachodniopomorskie        łobeski     Węgorzyno              47
2516  326101  zachodniopomorskie       Koszalin      Koszalin             219
2517  326201  zachodniopomorskie       Szczecin      Szczecin             890
2518  326301  zachodniopomorskie    Świnoujście   Świnoujście             120

[2519 rows x 5 columns]

In [10]:
powierzchnie=powierzchnie.iloc[:,:3]
powierzchnie

TERYT        Nazwa jednostki  Powierzchnia [ha]
0             00                 POLSKA           31393293
1             02      WOJ. DOLNOŚLĄSKIE            1994714
2        02 01     Powiat bolesławiecki             130351
3     02 01 01 1            Bolesławiec               2285
4     02 01 02 2            Bolesławiec              28913
...          ...                    ...                ...
4334  32 61 01 1            M. Koszalin              10557
4335     32 62       Powiat m. Szczecin              30062
4336  32 62 01 1            M. Szczecin              30062
4337     32 63    Powiat m. Świnoujście              20206
4338  32 63 01 1         M. Świnoujście              20206

[4339 rows x 3 columns]

In [11]:
populacja=populacja.iloc[8:,:3]
populacja.columns = ["Gmina", "TERYT", "Ludność"]
populacja

Gmina    TERYT Ludność
8        M.Bolesławiec  0201011   36795
9        G.Bolesławiec  0201022   15359
10          G.Gromadka  0201032    4978
11    M-W.Nowogrodziec  0201043   14523
12      M.Nowogrodziec  0201044    4050
...                ...      ...     ...
3917       M.Węgorzyno  3218054    2590
3918       G.Węgorzyno  3218055    3657
3919        M.Koszalin  3261011  105263
3920        M.Szczecin  3262011  386706
3921     M.Świnoujście  3263011   38541

[3914 rows x 3 columns]

In [12]:
alkohol=alkohol.iloc[:,3:6]
alkohol

Miejscowość                         Adres         Województwo
0                Warszawa  Aleja Rzeczypospolitej 18/83    WOJ. MAZOWIECKIE
1                 Kartuzy                ul. Zamkowa 23      WOJ. POMORSKIE
2               Ciechanów                 ul. Leśna 52     WOJ. MAZOWIECKIE
3           Bielsko-Biała     ul. Wincentego Witosa 170        WOJ. ŚLĄSKIE
4               Bieńkówka                 Bienkówka 454    WOJ. MAŁOPOLSKIE
..                    ...                           ...                 ...
411              Garwolin             ul. Parysowska 2     WOJ. MAZOWIECKIE
412                Gdańsk           ul. Jana z Kolna 11      WOJ. POMORSKIE
413                 Kępno                  Mianowice 1G  WOJ. WIELKOPOLSKIE
414  Stare Proboszczewice  ul. Stefana Mazowieckiego 18    WOJ. MAZOWIECKIE
415               Wolkowo             Maksymilianowo 40  WOJ. WIELKOPOLSKIE

[416 rows x 3 columns]

## agregacja datasetu alkohol

W datasecie alkohol interesuje nas jedynie sumarycznie ile jest w jakiej miejscowości hurtowników i ile jest hurtowników w jakim województwie.
Zagregujmy te dane.

In [13]:
alkohol_miejscowosc=alkohol["Miejscowość"].value_counts().reset_index()
alkohol_miejscowosc

Miejscowość  count
0                Warszawa     77
1                  Kraków     13
2                  Poznań     12
3                    Łódź     10
4                  Gdynia      7
..                    ...    ...
216              Szczytno      1
217              Garwolin      1
218                 Kępno      1
219  Stare Proboszczewice      1
220               Wolkowo      1

[221 rows x 2 columns]

In [14]:
alkohol_wojewodztwo=alkohol["Województwo"].value_counts().reset_index()
alkohol_wojewodztwo

Województwo  count
0           WOJ. MAZOWIECKIE    129
1         WOJ. WIELKOPOLSKIE     52
2           WOJ. MAŁOPOLSKIE     43
3               WOJ. ŚLĄSKIE     37
4             WOJ. POMORSKIE     28
5               WOJ. ŁÓDZKIE     19
6          WOJ. DOLNOŚLĄSKIE     18
7    WOJ. ZACHODNIOPOMORSKIE     15
8             WOJ. PODLASKIE     13
9    WOJ. KUJAWSKO-POMORSKIE     13
10            WOJ. LUBELSKIE     13
11         WOJ. PODKARPACKIE     12
12       WOJ. ŚWIĘTOKRZYSKIE      7
13  WOJ. WARMIŃSKO-MAZURSKIE      7
14             WOJ. OPOLSKIE      6
15             WOJ. LUBUSKIE      4

## Łączenie kodów gmin

Przejdźmy do najważniejszej części, czyli do łączenia kodów z 3 pierwszych datasetów. Tutaj bardzo przydatny będzie nasz pakiet preprocessor.

In [15]:
#usuńmy najpierw puste wiersze jeśli takie istanieją
populacja = ppr.usun_puste_wiersze(populacja)
powierzchnie = ppr.usun_puste_wiersze(powierzchnie)
pozary = ppr.usun_puste_wiersze(pozary)

INFO: usunięto 15 pustych wierszy.
INFO: usunięto 0 pustych wierszy.
INFO: usunięto 0 pustych wierszy.


In [16]:
len(populacja)

3899

In [17]:
len(powierzchnie)

4339

In [18]:
len(pozary)

2519

### POŻARY

Widzimy, że dataset pożary jest najkrótszy, więc będziemy się do niego dostosowywać. Pożary z opisu powinien zawierać tylko gminy,
ale gmin w 2024 roku było w Polsce 2477, więc mniej niż wierszy. W pierwszej kolejności znajdziemy jakie są dodatkowe wiersze w pożary,
a następnie przefiltrujemy pozostałe zbiory, żeby również uzyskać same gminy.

In [19]:
pozary[pozary["Gmina"]==pozary["Powiat"]]

TERYT         Województwo        Powiat         Gmina  Liczba Pożarów
165    26101        dolnośląskie  Jelenia Góra  Jelenia Góra             297
166    26201        dolnośląskie       Legnica       Legnica             500
167    26401        dolnośląskie       Wrocław       Wrocław             254
168    26402        dolnośląskie       Wrocław       Wrocław             431
169    26403        dolnośląskie       Wrocław       Wrocław             397
...      ...                 ...           ...           ...             ...
2404  306405       wielkopolskie        Poznań        Poznań             228
2405  306406       wielkopolskie        Poznań        Poznań             117
2516  326101  zachodniopomorskie      Koszalin      Koszalin             219
2517  326201  zachodniopomorskie      Szczecin      Szczecin             890
2518  326301  zachodniopomorskie   Świnoujście   Świnoujście             120

[103 rows x 5 columns]

Widzimy, że większe Miasta na prawach powiatu podzielone są na dzielnice. Uzyjemy więc dedykowanej funckcji do ich usunięcia i zagregowania danych

In [20]:
pozary=ppr.zlacz_dzielnice(pozary, "Liczba Pożarów")
pozary

INFO: Znaleziono 42 wierszy reprezentujących dzielnice.
INFO: Zakończono agregację. Usunięto: 37 wierszy.


TERYT    Województwo         Powiat         Gmina  Liczba Pożarów
0      20101   dolnośląskie  bolesławiecki   Bolesławiec              79
1      20102   dolnośląskie  bolesławiecki   Bolesławiec              75
2      20103   dolnośląskie  bolesławiecki      Gromadka              66
3      20104   dolnośląskie  bolesławiecki  Nowogrodziec             155
4      20105   dolnośląskie  bolesławiecki    Osiecznica              41
...      ...            ...            ...           ...             ...
2477  126101    małopolskie         Kraków        Kraków            1452
2478  306401  wielkopolskie         Poznań        Poznań            1024
2479  146501    mazowieckie       Warszawa      Warszawa            4252
2480   26401   dolnośląskie        Wrocław       Wrocław            1767
2481  106101        łódzkie           Łódź          Łódź            1585

[2482 rows x 5 columns]

Niestety dalej wierszy jest o 5 więcej niż gmin. Zobaczmy o co może chodzić. Może kody się gdzieś powtarzają.

In [21]:
ppr.znajdz_duplikaty(pozary, "TERYT")

       TERYT Województwo        Powiat      Gmina  Liczba Pożarów
347    60303   lubelskie      chełmski      Chełm              55
348    60303   lubelskie      chełmski      Sawin               0
609   100102     łódzkie  bełchatowski  Bełchatów              33
610   100102     łódzkie  bełchatowski  Kleszczów               0
1526  200209   podlaskie   białostocki   Grabówka              23
1527  200209   podlaskie   białostocki    Supraśl              18


Jak widać jest kilka duplikatów. Decyzję jak je połączyć podejmiemy później.

### POPULACJA

In [22]:
populacja

Gmina    TERYT Ludność
8        M.Bolesławiec  0201011   36795
9        G.Bolesławiec  0201022   15359
10          G.Gromadka  0201032    4978
11    M-W.Nowogrodziec  0201043   14523
12      M.Nowogrodziec  0201044    4050
...                ...      ...     ...
3917       M.Węgorzyno  3218054    2590
3918       G.Węgorzyno  3218055    3657
3919        M.Koszalin  3261011  105263
3920        M.Szczecin  3262011  386706
3921     M.Świnoujście  3263011   38541

[3899 rows x 3 columns]

Pierwszą obserwacją jest to, że kody gmin są dłuższe o jeden (lub o dwa, tam gdzie zaczynają się od zera).
Widzimy też, że każda gmina miejsko-wiejska, jest wpisana 3 razy- raz jako gmina, a następnie jako miasto i jako wieś.
Te dwa ostatnie rekordy sumują się do tego pierwszego. Poradzimy sobię z tym dedykowaną funkcją.

In [23]:
populacja=ppr.usun_rozdzielone_gminy_mw(populacja)
populacja

INFO: Usunięto 1422 wierszy z kolumny 'TERYT' kończących się na ['4', '5'].


Gmina    TERYT Ludność
8        M.Bolesławiec  0201011   36795
9        G.Bolesławiec  0201022   15359
10          G.Gromadka  0201032    4978
11    M-W.Nowogrodziec  0201043   14523
14        G.Osiecznica  0201052    7198
...                ...      ...     ...
3913         M-W.Resko  3218043    7083
3916     M-W.Węgorzyno  3218053    6247
3919        M.Koszalin  3261011  105263
3920        M.Szczecin  3262011  386706
3921     M.Świnoujście  3263011   38541

[2477 rows x 3 columns]

In [24]:
len(populacja)

2477

Jak widać pozostało 2477 wierszy, czyli dokładnie tyle ile było gmin w roku 2024.

Usuńmy ostatnią cyfrę dla zgodności z pozary.

In [25]:
populacja=ppr.usun_ostatnia_cyfre(populacja,"TERYT")
populacja

INFO: Usunięto ostatnią cyfrę w kolumnie 'TERYT'.


Gmina   TERYT Ludność
8        M.Bolesławiec  020101   36795
9        G.Bolesławiec  020102   15359
10          G.Gromadka  020103    4978
11    M-W.Nowogrodziec  020104   14523
14        G.Osiecznica  020105    7198
...                ...     ...     ...
3913         M-W.Resko  321804    7083
3916     M-W.Węgorzyno  321805    6247
3919        M.Koszalin  326101  105263
3920        M.Szczecin  326201  386706
3921     M.Świnoujście  326301   38541

[2477 rows x 3 columns]

### POWIERZCHNIE

In [26]:
powierzchnie

TERYT        Nazwa jednostki  Powierzchnia [ha]
0             00                 POLSKA           31393293
1             02      WOJ. DOLNOŚLĄSKIE            1994714
2        02 01     Powiat bolesławiecki             130351
3     02 01 01 1            Bolesławiec               2285
4     02 01 02 2            Bolesławiec              28913
...          ...                    ...                ...
4334  32 61 01 1            M. Koszalin              10557
4335     32 62       Powiat m. Szczecin              30062
4336  32 62 01 1            M. Szczecin              30062
4337     32 63    Powiat m. Świnoujście              20206
4338  32 63 01 1         M. Świnoujście              20206

[4339 rows x 3 columns]

Widzimy, że kody mają odstępy, zacznijmy od ich usunięcia.

In [27]:
powierzchnie=ppr.usun_odstepy(powierzchnie)
powierzchnie

INFO: Usunięto odstępy z kolumny 'TERYT'.


TERYT        Nazwa jednostki  Powierzchnia [ha]
0          00                 POLSKA           31393293
1          02      WOJ. DOLNOŚLĄSKIE            1994714
2        0201   Powiat bolesławiecki             130351
3     0201011            Bolesławiec               2285
4     0201022            Bolesławiec              28913
...       ...                    ...                ...
4334  3261011            M. Koszalin              10557
4335     3262     Powiat m. Szczecin              30062
4336  3262011            M. Szczecin              30062
4337     3263  Powiat m. Świnoujście              20206
4338  3263011         M. Świnoujście              20206

[4339 rows x 3 columns]

Jak widać mamy tutaj nie tylko gminy, ale również zagregowane z Powiatów i Województw (mają one krótsze kody), zatem usuńmy te wiersze dedykowaną funkcją.

In [28]:
powierzchnie=ppr.usun_krotkie(powierzchnie)
powierzchnie

INFO: W kolumnie 'TERYT' usunięto 397 wierszy.


TERYT             Nazwa jednostki  Powierzchnia [ha]
3     0201011                 Bolesławiec               2285
4     0201022                 Bolesławiec              28913
5     0201032                    Gromadka              26775
6     0201043                Nowogrodziec              17663
7     0201044       Nowogrodziec - miasto               1610
...       ...                         ...                ...
4331  3218054          Węgorzyno - miasto                685
4332  3218055  Węgorzyno - obszar wiejski              24934
4334  3261011                 M. Koszalin              10557
4336  3262011                 M. Szczecin              30062
4338  3263011              M. Świnoujście              20206

[3942 rows x 3 columns]

Widzimy, że ponownie rozdzielone są gminy miejsko-wiejskie.

In [29]:
powierzchnie=ppr.usun_rozdzielone_gminy_mw(powierzchnie)
powierzchnie

INFO: Usunięto 1436 wierszy z kolumny 'TERYT' kończących się na ['4', '5'].


TERYT Nazwa jednostki  Powierzchnia [ha]
3     0201011     Bolesławiec               2285
4     0201022     Bolesławiec              28913
5     0201032        Gromadka              26775
6     0201043    Nowogrodziec              17663
9     0201052      Osiecznica              43669
...       ...             ...                ...
4327  3218043           Resko              28519
4330  3218053       Węgorzyno              25619
4334  3261011     M. Koszalin              10557
4336  3262011     M. Szczecin              30062
4338  3263011  M. Świnoujście              20206

[2506 rows x 3 columns]

Znaleźliśmy miejsca w których duże miasta rozdzielone są na dzielnice w taki sposób że ich kod kończy się na 8 lub 9, a ich zagregowana wartość znajduje się
w innym wierszu. Usuńmy te niepotrzebne wiersze dedykowaną funkcją.

In [30]:
powierzchnie=ppr.usun_dzielnice_miast(powierzchnie)
powierzchnie

INFO: Usunięto 27 wierszy z kolumny 'TERYT' kończących się na ['8', '9'].


TERYT Nazwa jednostki  Powierzchnia [ha]
3     0201011     Bolesławiec               2285
4     0201022     Bolesławiec              28913
5     0201032        Gromadka              26775
6     0201043    Nowogrodziec              17663
9     0201052      Osiecznica              43669
...       ...             ...                ...
4327  3218043           Resko              28519
4330  3218053       Węgorzyno              25619
4334  3261011     M. Koszalin              10557
4336  3262011     M. Szczecin              30062
4338  3263011  M. Świnoujście              20206

[2479 rows x 3 columns]

usuńmy ostatnią cyfrę dla ujednolicenia kodów

In [31]:
powierzchnie=ppr.usun_ostatnia_cyfre(powierzchnie, "TERYT")
powierzchnie

INFO: Usunięto ostatnią cyfrę w kolumnie 'TERYT'.


TERYT Nazwa jednostki  Powierzchnia [ha]
3     020101     Bolesławiec               2285
4     020102     Bolesławiec              28913
5     020103        Gromadka              26775
6     020104    Nowogrodziec              17663
9     020105      Osiecznica              43669
...      ...             ...                ...
4327  321804           Resko              28519
4330  321805       Węgorzyno              25619
4334  326101     M. Koszalin              10557
4336  326201     M. Szczecin              30062
4338  326301  M. Świnoujście              20206

[2479 rows x 3 columns]

Widizmy, że pozostały dwa wiersze więcej, niż było gmin w roku 2024. Sprawdźmy co to za wiersze i czy reszta wierszy zgadza się ze zbiorem populacja.

In [32]:
ppr.sprawdz_zgodnosc(powierzchnie, populacja, "TERYT")

INFO: Wszystkie wiersze z drugiego DataFrame mają odpowiedniki w pierwszym.


       TERYT Nazwa jednostki  Powierzchnia [ha]
1440  120713         Szczawa               4238
2629  200216        Grabówka               6464


Po wyszukaniu tych gmin okazuje się, że gmina Szczawa była częścią gminy Kamienica, a gmina Grabówka była częścią gminy Supraśl. Obie odłączyły się w 2025 roku.
Dołączymy więc te gminy, do ich starych nazw, sumując kolumny z powierzchnią. Użyjemy w tym celu dedykowanej funkcji. Sprawdźmy tylko najpierw, czy nie ma wielu gmin o tej samej nazwie.

In [33]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Supraśl"]

TERYT Nazwa jednostki  Powierzchnia [ha]
2612  200209         Supraśl              12392

In [34]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Kamienica"]

TERYT Nazwa jednostki  Powierzchnia [ha]
1432  120705       Kamienica               5286

In [35]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Szczawa"]

TERYT Nazwa jednostki  Powierzchnia [ha]
1440  120713         Szczawa               4238

In [36]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Grabówka"]

TERYT Nazwa jednostki  Powierzchnia [ha]
2629  200216        Grabówka               6464

skoro każda z gmin ma unikalną nazwę, to możemy użyć funkcji, która złączy je po nazwie. W przeciwnym wypadku musielibyśmy łączyć je po kodach TERYT.

In [37]:
powierzchnie=ppr.zlacz_gminy(powierzchnie,"Kamienica", "Szczawa", "Powierzchnia [ha]", "Nazwa jednostki")

INFO: Połączono gminę 'Szczawa' z 'Kamienica'. Dodano wartość 4238 do kolumny 'Powierzchnia [ha]'.


In [38]:
powierzchnie=ppr.zlacz_gminy(powierzchnie,"Supraśl", "Grabówka", "Powierzchnia [ha]", "Nazwa jednostki")

INFO: Połączono gminę 'Grabówka' z 'Supraśl'. Dodano wartość 6464 do kolumny 'Powierzchnia [ha]'.


In [39]:
len(powierzchnie)

2477

zgadza się liczba wierszy, sprawdźmy ponownie zgodność kodów ze zbiorem populacja.

In [40]:
ppr.sprawdz_zgodnosc(powierzchnie, populacja, "TERYT")

INFO: Wszystkie wiersze z pierwszego DataFrame mają odpowiedniki w drugim.
INFO: Wszystkie wiersze z drugiego DataFrame mają odpowiedniki w pierwszym.
INFO: Pełna spójność kluczy w kolumnie 'TERYT' między oboma DataFrame'ami.


Wróćmy zatem do zbioru pozary.

### POŻARY 2

Aby móc zestawić ze sobą kody, musimy najpierw pozbyć się zer (na początku) w kodach populacji i powierzchni. Zamieńmy zatem wszystkie wartości na inty.

In [41]:
populacja=ppr.str_to_int(populacja, "TERYT")

In [42]:
powierzchnie=ppr.str_to_int(powierzchnie, "TERYT")

Zacznijmy od znalezionych wcześniej duplikatów.

In [43]:
ppr.znajdz_duplikaty(pozary, "TERYT")

       TERYT Województwo        Powiat      Gmina  Liczba Pożarów
347    60303   lubelskie      chełmski      Chełm              55
348    60303   lubelskie      chełmski      Sawin               0
609   100102     łódzkie  bełchatowski  Bełchatów              33
610   100102     łódzkie  bełchatowski  Kleszczów               0
1526  200209   podlaskie   białostocki   Grabówka              23
1527  200209   podlaskie   białostocki    Supraśl              18


In [44]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Sawin"]

TERYT Nazwa jednostki  Powierzchnia [ha]
621  60310           Sawin              18766

In [45]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Chełm"]

TERYT Nazwa jednostki  Powierzchnia [ha]
614  60303           Chełm              22267

In [46]:
pozary[pozary["Gmina"]=="Sawin"]

TERYT Województwo    Powiat  Gmina  Liczba Pożarów
348  60303   lubelskie  chełmski  Sawin               0
355  60310   lubelskie  chełmski  Sawin              24

Widzimy, że gminę Sawin wpisano w pożary dwukrotnie, raz z błędym kodem. Musimy zatem usunąć ten wiersz.

In [47]:
pozary=pozary.drop(348)

In [48]:
ppr.znajdz_duplikaty(pozary, "TERYT")

       TERYT Województwo        Powiat      Gmina  Liczba Pożarów
609   100102     łódzkie  bełchatowski  Bełchatów              33
610   100102     łódzkie  bełchatowski  Kleszczów               0
1526  200209   podlaskie   białostocki   Grabówka              23
1527  200209   podlaskie   białostocki    Supraśl              18


In [49]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Bełchatów"]

TERYT Nazwa jednostki  Powierzchnia [ha]
1044  100101       Bełchatów               3464
1045  100102       Bełchatów              20106

In [50]:
pozary[pozary["Gmina"]=="Bełchatów"]

TERYT Województwo        Powiat      Gmina  Liczba Pożarów
608  100101     łódzkie  bełchatowski  Bełchatów              68
609  100102     łódzkie  bełchatowski  Bełchatów              33

In [51]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Kleszczów"]

TERYT Nazwa jednostki  Powierzchnia [ha]
1047  100104       Kleszczów              10403

In [52]:
pozary[pozary["Gmina"]=="Kleszczów"]

TERYT Województwo        Powiat      Gmina  Liczba Pożarów
610  100102     łódzkie  bełchatowski  Kleszczów               0
612  100104     łódzkie  bełchatowski  Kleszczów               8

Dokładnie to samo stało się z gminą Kleszczów.

In [53]:
pozary=pozary.drop(610)

In [54]:
ppr.znajdz_duplikaty(pozary, "TERYT")

       TERYT Województwo       Powiat     Gmina  Liczba Pożarów
1526  200209   podlaskie  białostocki  Grabówka              23
1527  200209   podlaskie  białostocki   Supraśl              18


In [55]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Grabówka"]

Empty DataFrame
Columns: [TERYT, Nazwa jednostki, Powierzchnia [ha]]
Index: []

In [56]:
pozary[pozary["Gmina"]=="Grabówka"]

TERYT Województwo       Powiat     Gmina  Liczba Pożarów
1526  200209   podlaskie  białostocki  Grabówka              23

In [57]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Supraśl"]

TERYT Nazwa jednostki  Powierzchnia [ha]
2612  200209         Supraśl              18856

In [58]:
pozary[pozary["Gmina"]=="Supraśl"]

TERYT Województwo       Powiat    Gmina  Liczba Pożarów
1527  200209   podlaskie  białostocki  Supraśl              18
1534  200216   podlaskie  białostocki  Supraśl               5

200216 jest nowym kodem wpisanym gminie Grabówka, która odłączyła się od gminy Supraśl. Zrobione zostały zatem dwa błędy. Jednocześnie gmina Supraśl została wpisana 2 razy, raz jako Supraśl+Grabówka przed rozłamem i raz jako Supraśl, natomiast kod grabówki i supraśl został zamieniony.
Musimy usunąć wiersz Grabówka i połączyć wiersze Supraśl

In [59]:
pozary=pozary.drop(1526)

In [60]:
pozary=ppr.zlacz_gminy(pozary, 200209, 200216, "Liczba Pożarów", "TERYT")

INFO: Połączono gminę '200216' z '200209'. Dodano wartość 5 do kolumny 'Liczba Pożarów'.


In [61]:
ppr.znajdz_duplikaty(pozary, "TERYT")

INFO: Brak zduplikowanych wartości w kolumnie 'TERYT'.


Sprawdźmy teraz jak wygląda zgodność między kodami.

In [62]:
ppr.sprawdz_zgodnosc(pozary, populacja, "TERYT")

INFO: Wszystkie wiersze z drugiego DataFrame mają odpowiedniki w pierwszym.


      TERYT  Województwo      Powiat      Gmina  Liczba Pożarów
852  120713  małopolskie  limanowski  Kamienica               3


In [63]:
powierzchnie[powierzchnie["Nazwa jednostki"]=="Kamienica"]

TERYT Nazwa jednostki  Powierzchnia [ha]
1432  120705       Kamienica               9524

In [64]:
pozary[pozary["Gmina"]=="Kamienica"]

TERYT  Województwo      Powiat      Gmina  Liczba Pożarów
844  120705  małopolskie  limanowski  Kamienica               5
852  120713  małopolskie  limanowski  Kamienica               3

Kod 120713 jest nadany gminie Szczawa, która odłączyła się w 2025 roku od gminy Kamienica. Zapisana została zatem stara nazwa. Musimy połączyć te dwa wiersze.

In [65]:
pozary=ppr.zlacz_gminy(pozary, 120705, 120713, "Liczba Pożarów", "TERYT")

INFO: Połączono gminę '120713' z '120705'. Dodano wartość 3 do kolumny 'Liczba Pożarów'.


In [66]:
ppr.sprawdz_zgodnosc(pozary, populacja, "TERYT")

INFO: Wszystkie wiersze z pierwszego DataFrame mają odpowiedniki w drugim.
INFO: Wszystkie wiersze z drugiego DataFrame mają odpowiedniki w pierwszym.
INFO: Pełna spójność kluczy w kolumnie 'TERYT' między oboma DataFrame'ami.


Udało się połączyć wszystkie kody!

### Łączenie zbiorów

Stwórzmy jeden złączony Dataframe z tych trzech zbiorów.

In [67]:
wszystkie_dane=pd.merge(pozary, powierzchnie[['TERYT', 'Powierzchnia [ha]']], on='TERYT', how='left')

In [68]:
wszystkie_dane=pd.merge(wszystkie_dane, populacja[['TERYT', 'Ludność']], on='TERYT', how='left')

In [69]:
wszystkie_dane

TERYT    Województwo         Powiat         Gmina  Liczba Pożarów  \
0      20101   dolnośląskie  bolesławiecki   Bolesławiec              79   
1      20102   dolnośląskie  bolesławiecki   Bolesławiec              75   
2      20103   dolnośląskie  bolesławiecki      Gromadka              66   
3      20104   dolnośląskie  bolesławiecki  Nowogrodziec             155   
4      20105   dolnośląskie  bolesławiecki    Osiecznica              41   
...      ...            ...            ...           ...             ...   
2472  126101    małopolskie         Kraków        Kraków            1452   
2473  306401  wielkopolskie         Poznań        Poznań            1024   
2474  146501    mazowieckie       Warszawa      Warszawa            4252   
2475   26401   dolnośląskie        Wrocław       Wrocław            1767   
2476  106101        łódzkie           Łódź          Łódź            1585   

      Powierzchnia [ha]  Ludność  
0                  2285    36795  
1                 28913    15359  
2                 26775     4978  
3                 17663    14523  
4                 43669     7198  
...                 ...      ...  
2472              32685   809168  
2473              26192   536151  
2474              51720  1863845  
2475              29279   672882  
2476              29325   645693  

[2477 rows x 7 columns]

Nie będziemy już potrzebować kolumny TERYT i Powiat, więc usuńmy je dla klarowności

In [70]:
wszystkie_dane=wszystkie_dane.drop(['TERYT', 'Powiat'], axis=1)
wszystkie_dane

Województwo         Gmina  Liczba Pożarów  Powierzchnia [ha]  Ludność
0      dolnośląskie   Bolesławiec              79               2285    36795
1      dolnośląskie   Bolesławiec              75              28913    15359
2      dolnośląskie      Gromadka              66              26775     4978
3      dolnośląskie  Nowogrodziec             155              17663    14523
4      dolnośląskie    Osiecznica              41              43669     7198
...             ...           ...             ...                ...      ...
2472    małopolskie        Kraków            1452              32685   809168
2473  wielkopolskie        Poznań            1024              26192   536151
2474    mazowieckie      Warszawa            4252              51720  1863845
2475   dolnośląskie       Wrocław            1767              29279   672882
2476        łódzkie          Łódź            1585              29325   645693

[2477 rows x 5 columns]

przygotujmy jeszcze zagregowane dane na poziomie Województw do analizy z danymi alkohol

In [78]:
wszystkie_dane_wojewodztwo= wszystkie_dane.groupby('Województwo').agg({
    'Liczba Pożarów': 'sum',
    'Powierzchnia [ha]': 'sum',
    'Ludność': 'sum'
}).reset_index()
wszystkie_dane_wojewodztwo

Województwo  Liczba Pożarów  Powierzchnia [ha]  Ludność
0          dolnośląskie           10957            1994714  2868242
1    kujawsko-pomorskie            5223            1797141  1984479
2             lubelskie            5675            2512244  1996440
3              lubuskie            3476            1398756   969819
4           mazowieckie           17321            3555861  5508322
5           małopolskie            6849            1518358  3429084
6              opolskie            2641             941155   930296
7          podkarpackie            5078            1784539  2062997
8             podlaskie            3164            2018683  1132641
9             pomorskie            5467            1954680  2359493
10  warmińsko-mazurskie            3974            2417367  1349172
11        wielkopolskie            7688            2982678  3479986
12   zachodniopomorskie            5428            2290930  1622760
13              łódzkie            6781            1821894  2345924
14              śląskie           10197            1233404  4291441
15       świętokrzyskie            3697            1170889  1157991

dopasujmy nazwy w zbiorze alkohole_wojewodztwo

In [72]:
alkohol_wojewodztwo=ppr.usun_woj(alkohol_wojewodztwo)
alkohol_wojewodztwo=ppr.litery_na_male(alkohol_wojewodztwo)
alkohol_wojewodztwo

INFO: Usunięto prefiks 'WOJ. ' z kolumny 'Województwo'.
INFO: Zmieniono litery na małe w kolumnie 'Województwo'.


Województwo  count
0           mazowieckie    129
1         wielkopolskie     52
2           małopolskie     43
3               śląskie     37
4             pomorskie     28
5               łódzkie     19
6          dolnośląskie     18
7    zachodniopomorskie     15
8             podlaskie     13
9    kujawsko-pomorskie     13
10            lubelskie     13
11         podkarpackie     12
12       świętokrzyskie      7
13  warmińsko-mazurskie      7
14             opolskie      6
15             lubuskie      4

dopasujmy też gminy miejskie, które są w alkohol_miejscowosc

In [75]:
wszystkie_dane_miejscowosc=wszystkie_dane[wszystkie_dane["Gmina"].isin(alkohol_miejscowosc["Miejscowość"])]
wszystkie_dane_miejscowosc

Województwo              Gmina  Liczba Pożarów  Powierzchnia [ha]  \
7      dolnośląskie        Dzierżoniów              83               2007   
10     dolnośląskie        Dzierżoniów              28              14107   
47     dolnośląskie  Bystrzyca Kłodzka              49              33854   
64     dolnośląskie              Lubań              86               1612   
67     dolnośląskie              Lubań              45              14242   
...             ...                ...             ...                ...   
2472    małopolskie             Kraków            1452              32685   
2473  wielkopolskie             Poznań            1024              26192   
2474    mazowieckie           Warszawa            4252              51720   
2475   dolnośląskie            Wrocław            1767              29279   
2476        łódzkie               Łódź            1585              29325   

      Ludność  
7       30312  
10       9109  
47      17074  
64      19257  
67       6462  
...       ...  
2472   809168  
2473   536151  
2474  1863845  
2475   672882  
2476   645693  

[211 rows x 5 columns]

In [77]:
wszystkie_dane_miejscowosc = wszystkie_dane_miejscowosc.groupby('Gmina').agg({
    'Liczba Pożarów': 'sum',
    'Powierzchnia [ha]': 'sum',
    'Ludność': 'sum'
}).reset_index()

In [78]:
wszystkie_dane_miejscowosc

Gmina  Liczba Pożarów  Powierzchnia [ha] Ludność
0          Białogard              80              35399   29384
1          Białystok             349              10213  290386
2    Bielsk Podlaski              89              45695   29914
3      Bielsko-Biała             208              12445  164318
4           Bodzanów              32              13633    7699
..               ...             ...                ...     ...
166          Świdnik              38               2035   36468
167      Świnoujście             120              20206   38541
168         Żelazków              17              11365    9580
169         Żyrardów             115               1435   38401
170           Żywiec              64               5048   29419

[171 rows x 4 columns]

Mamy już przygotowane wszystkie dane do analizy.